### ISSUE TITLE
how to get appropiate alpha value

### ISSUE THREAD

**Issue by ramdhan1989** [tuda-geo/dageo#20]
Hi,
is there a way to find the appropiate alpha value? I got either the prior is not changing or it change drasticaly become unrelalistic result.

**Comment by prisae** [comment]
The default, `alpha=4`, should work most of the time.
Emerick had in his original paper some other suggestions:
- `alpha=[9.333, 7.0, 4.0, 2.0]`;
- `alpha=[20.719, 19.0, 17.0, 16.0, 15.0, 9.0, 5.0, 2.5]`;
- `alpha=[57.017, 35.0, 25.0, 20.0, 18.0, 15.0, 12.0, 8.0, 5.0, 3.0]`.

What is important is that you have to insure that `sum(1/alpha) = 1`, otherwise your result will be wrong.

**Comment by ramdhan1989** [comment]
Well noted, thanks for your help again.
